source "https://rubygems.org"

gem "metanorma-cli"
gem "metanorma-ribose", github: "metanorma/metanorma-ribose", branch: "main"
gem "metanorma-generic", github: "metanorma/metanorma-generic", branch: "main"
gem "metanorma-standoc", github: "metanorma/metanorma-standoc", branch: "main"
gem "isodoc", github: "metanorma/isodoc", branch: "main"
gem "isodoc-i18n", github: "metanorma/isodoc-i18n", branch: "main"
gem "metanorma", github: "metanorma/metanorma", branch: "main"
gem "relaton", "= 3.0.0.pre.alpha.11"
gem "relaton-render", "= 3.0.0.pre.alpha.19"
gem "relaton-bib", "2.2.0.pre.alpha.1"
gem "pubid", github: "pubid/pubid", branch: "main"
gem "moxml", github: "lutaml/moxml", branch: "main"
gem "leptris", "1.9.317"
